FROM ubuntu:22.04

ARG TARGETARCH

RUN apt-get update && apt-get install -y ca-certificates && apt-get clean

COPY target/${TARGETARCH}/clickhouse-ddl /clickhouse-ddl
RUN chmod 0755 /clickhouse-ddl

ENTRYPOINT ["/clickhouse-ddl"]
